### ISSUE TITLE
How to use inline comments?

### ISSUE THREAD

**Issue by bellebethcooper** [mint-lang/mint-vscode#26]
Hello!

I noticed inline comments support was added after version `0.5.0` and I can't see a version bump since then. Is there a way to manually install the latest version of the extension into VS Code, or do we need to wait for a version bump? I don't have any experience with VS Code extensions, but if a version bump is required and fairly simple, I'm happy to give it a go and submit a PR.

Thanks!

**Comment by gdotdesign** [comment]
Hi :wave: Thanks for letting me know, I've bumped the version and released 0.6.0 :rocket:

**Comment by bellebethcooper** [comment]
Great, thanks for that!
