### ISSUE TITLE
CSS highlighting & autocomplete

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint-vscode#3]
What do we need to enable CSS highlighting & autocomplete in syntax highlighting? Can we somehow pipe Emmet in?

**Comment by s0kil** [comment]
CSS highlighting could be done similar to how we handle HTML, as [an embedded language](https://github.com/s0kil/mint-vscode/blob/master/syntaxes/mint.tmLanguage.yaml#L33-L45)

Autocomplete would be more difficult, and I would like for [this](https://github.com/mint-lang/mint/issues/260) feature to be implemented first.
This would allow the language server to provide smart results based on the context. For example, we would know that `width` accepts [CSS Units](https://www.w3schools.com/cssref/css_units.asp) and we could also provide autocomplete when using arguments:
```mint
  style base(color : String) {
    color: #{color};
	width: #{color} <- Color does not make sense here
  }
```

**Comment by s0kil** [comment]
We could use something like [this](https://github.com/atom/language-html/blob/master/grammars/html.cson#L131-L143), how HTML handles `<style>` tag highlighting.

**Comment by lukepighetti** [comment]
Honestly if we highlight the `css-property:` part of `css-property: value;` that should be sufficient for the time being imo.

**Comment by gdotdesign** [comment]
@s0kil @lukepighetti I think with #21 this issue is resolved?

**Comment by lukepighetti** [comment]
As pictured in #21 this issue is resolved
